services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    deploy:
      replicas: $API_REPLICAS
    depends_on:
      - postgresdb
    build:
      context: ./server
      dockerfile: Dockerfile-dev
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DB_HOST=postgresdb
      - DB_USER=$POSTGRESDB_USER
      - DB_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - DB_NAME=$POSTGRESDB_DATABASE
      - DB_PORT=$POSTGRESDB_LOCAL_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./server:/server
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    depends_on:
      - app
    ports:
      - 80:80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db:
