services:
  postgresdb:
    image: postgis/postgis
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    depends_on:
      - postgresdb
    build:
      context: ./server
      dockerfile: Dockerfile-dev
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DB_HOST=postgresdb
      - DB_USER=$POSTGRESDB_USER
      - DB_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - DB_NAME=$POSTGRESDB_DATABASE
      - DB_PORT=$POSTGRESDB_LOCAL_PORT
    stdin_open: true
    tty: true
    expose:
      - $API_PORT
    ports:
      - $API_PORT:$API_PORT
    volumes:
      - ./server:/server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db:
