# Use an official Node runtime as a parent image
FROM node:20

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Copy the rest of your app's source code
COPY . .

# Define the command to run your app using CMD which defines your runtime
CMD npm ci --only=production && npm start